# Generated by Django 4.2.3 on 2023-07-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
